<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>RinNpc.Mono</AssemblyName>
    <RootNamespace>RinNpcExample.Mono</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../RinNpc.Core/RinNpc.Core.csproj" />
    <PackageReference Include="BepInEx.Unity.Mono"
                      Version="[6.0.0-be.785]"
                      IncludeAssets="compile" />
    <PackageReference Include="UnityEngine.Modules"
                      Version="[5.6.1]"
                      IncludeAssets="compile" />
  </ItemGroup>
</Project>
