<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>RinNpc.Core.Tests</AssemblyName>
    <RootNamespace>RinNpcExample.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../RinNpc.Core/RinNpc.Core.csproj" />
  </ItemGroup>
</Project>
