<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>RinNpc.IL2CPP</AssemblyName>
    <RootNamespace>RinNpcExample.IL2CPP</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../RinNpc.Core/RinNpc.Core.csproj" />
    <PackageReference Include="BepInEx.Unity.IL2CPP"
                      Version="[6.0.0-be.785]"
                      IncludeAssets="compile" />
  </ItemGroup>
</Project>
