<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="UnityStubs.cs" />
    <Compile Include="Program.cs" />
    <Compile Include="../../examples/unity/RinClient.cs" Link="RinClient.cs" />
    <Compile Include="../../examples/unity/RinUnityWorkflow.cs" Link="RinUnityWorkflow.cs" />
    <Compile Include="../../examples/unity/RinNpcExample.cs" Link="RinNpcExample.cs" />
  </ItemGroup>
</Project>
